-- Altera numero de GENERATED ALWAYS para GENERATED BY DEFAULT
-- para permitir inserir o numero manualmente (baseado no ultimo pedido do Bubble)

ALTER TABLE public.pedidos
  ALTER COLUMN numero SET GENERATED BY DEFAULT;
